ALTER TABLE companies
ALTER COLUMN company_id
ADD GENERATED  ALWAYS AS IDENTITY (START WITH 7);

ALTER TABLE projects
ALTER COLUMN project_id
ADD GENERATED  ALWAYS AS IDENTITY (START WITH 9);

ALTER TABLE developers
ALTER COLUMN dev_id
ADD GENERATED  ALWAYS AS IDENTITY (START WITH 8);

ALTER TABLE skills
ALTER COLUMN company_id
ADD GENERATED  ALWAYS AS IDENTITY (START WITH 13);

ALTER TABLE customers
ALTER COLUMN customer_id
ADD GENERATED  ALWAYS AS IDENTITY (START WITH 7);

ALTER TABLE projects
DROP CONSTRAINT fk_customer,
ADD CONSTRAINT fk_customer FOREIGN KEY(customer_id) REFERENCES customers(customer_id)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE developers_projects
DROP  CONSTRAINT fk_dp_dev,
DROP  CONSTRAINT fk_dp_proj,
ADD  CONSTRAINT fk_dp_dev FOREIGN KEY(dev_id) REFERENCES developers(dev_id)
 ON UPDATE CASCADE
 ON DELETE CASCADE,
ADD  CONSTRAINT fk_dp_proj FOREIGN KEY(project_id) REFERENCES projects(project_id)
ON UPDATE CASCADE
 ON DELETE CASCADE;

ALTER TABLE developers_skills
DROP	CONSTRAINT fk_ds_dev,
DROP    CONSTRAINT fk_ds_skill,
ADD	CONSTRAINT fk_ds_dev FOREIGN KEY(dev_id) REFERENCES developers(dev_id)
ON UPDATE CASCADE
 ON DELETE CASCADE,
ADD	CONSTRAINT fk_ds_skill FOREIGN KEY(skill_id) REFERENCES skills(skill_id)
ON UPDATE CASCADE
 ON DELETE CASCADE;

ALTER TABLE companies_projects
DROP	CONSTRAINT fk_cp_comp,
DROP	CONSTRAINT fk_cp_proj,
ADD	CONSTRAINT fk_cp_comp FOREIGN KEY(company_id) REFERENCES companies(company_id)
 ON UPDATE CASCADE
 ON DELETE CASCADE,
ADD	CONSTRAINT fk_cp_proj FOREIGN KEY(project_id) REFERENCES projects(project_id))
ON UPDATE CASCADE
 ON DELETE CASCADE;

ALTER  TABLE customers_projects
DROP	CONSTRAINT fk_cup_comp,
DROP  CONSTRAINT fk_cup_proj,
ADD	CONSTRAINT fk_cup_comp FOREIGN KEY(customer_id) REFERENCES customers(customer_id)
ON UPDATE CASCADE
 ON DELETE CASCADE,
ADD	CONSTRAINT fk_cup_proj FOREIGN KEY(project_id) REFERENCES projects(project_id)
ON UPDATE CASCADE
 ON DELETE CASCADE;


